background="default"
text="#f8f8f2"
subtle="#8aff80"
warning-text="#282a36"
text-special-one="#bd93f9"
text-special-two="#ff79c6"
top-bar-background="#282a36"
top-bar-text="#f8f8f2"
status-bar-background="#282a36"
status-bar-text="#f8f8f2"
status-bar-view-background="#bd93f9"
status-bar-view-text="#f8f8f2"
command-text="#f8f8f2"
list-selected-background="#bd93f9"
list-selected-text="#f8f8f2"
list-selected-inactive-background="#282a36"
list-selected-inactive-text="#f8f8f2"
controls-text="#f8f8f2"
controls-highlight="#bd93f9"
autocomplete-background="#272822"
autocomplete-text="#f8f8f2"
autocomplete-selected-background="#bd93f9"
autocomplete-selected-text="#f8f8f2"
button-color-one="#282a36"
button-color-two="#272822"
timeline-name-background="#272822"
timeline-name-text="#8aff80"
